import { Link, useParams } from "react-router-dom";
import { ArrowLeft, ArrowRight, Check, ShieldCheck, Sparkles } from "lucide-react";
import Footer from "../components/Footer";
import ThemeSwitcher from "../components/ThemeSwitcher";
import LanguageSwitcher from "../components/LanguageSwitcher";
import { useLanguage } from "../hooks/useLanguage";
import logo from "../assets/ledgerflow.webp";

type Detail = { id: string; en: { title: string; description: string; points: string[] }; idText: { title: string; description: string; points: string[] } };
const details: Record<string, Detail[]> = {
  solutions: [
    { id: "small-businesses", en: { title: "Accounting built for small businesses", description: "Keep every transaction, invoice, and financial report in one calm, reliable place.", points: ["Simple day-to-day bookkeeping", "Real-time business visibility", "Ready-to-export reports"] }, idText: { title: "Akuntansi untuk usaha kecil", description: "Simpan transaksi, invoice, dan laporan keuangan dalam satu tempat yang rapi dan andal.", points: ["Pembukuan harian yang sederhana", "Visibilitas bisnis real-time", "Laporan siap diekspor"] } },
    { id: "mid-market-companies", en: { title: "Control for growing companies", description: "Bring entities, teams, and financial decisions together as your company scales.", points: ["Multi-entity reporting", "Approval-ready workflows", "Clear audit history"] }, idText: { title: "Kontrol untuk perusahaan berkembang", description: "Satukan entitas, tim, dan keputusan keuangan saat perusahaan Anda berkembang.", points: ["Laporan multi-entitas", "Alur persetujuan", "Riwayat audit jelas"] } },
    { id: "accountants-firms", en: { title: "A better client workspace", description: "Serve every client from a structured workspace with clean, current books.", points: ["Separate client workspaces", "Collaborative access", "Faster month-end close"] }, idText: { title: "Workspace klien yang lebih baik", description: "Layani setiap klien dari workspace terstruktur dengan pembukuan yang rapi dan terkini.", points: ["Workspace klien terpisah", "Akses kolaboratif", "Tutup buku lebih cepat"] } },
    { id: "startups", en: { title: "Financial clarity from day one", description: "Build dependable financial habits before your next funding milestone.", points: ["Track burn and runway", "Investor-ready reports", "A scalable chart of accounts"] }, idText: { title: "Kejelasan keuangan sejak hari pertama", description: "Bangun kebiasaan keuangan yang andal sebelum milestone pendanaan berikutnya.", points: ["Pantau burn dan runway", "Laporan siap investor", "Chart of accounts yang scalable"] } },
  ],
  products: [
    { id: "chart-of-accounts", en: { title: "A chart of accounts that stays organized", description: "Create a flexible account structure that reflects how your business actually operates.", points: ["Custom account structure", "Clear categorisation", "Built for reporting"] }, idText: { title: "Chart of accounts yang selalu rapi", description: "Buat struktur akun fleksibel yang sesuai dengan cara bisnis Anda berjalan.", points: ["Struktur akun kustom", "Kategorisasi jelas", "Siap untuk laporan"] } },
    { id: "journal-entries", en: { title: "Confident double-entry journals", description: "Record, review, and trace every journal entry with balanced accounting built in.", points: ["Automatic balance checks", "Detailed audit trail", "Fast review workflow"] }, idText: { title: "Jurnal double-entry yang andal", description: "Catat, tinjau, dan telusuri setiap jurnal dengan akuntansi seimbang bawaan.", points: ["Pengecekan saldo otomatis", "Audit trail detail", "Alur review cepat"] } },
    { id: "financial-reports", en: { title: "Financial reports without the wait", description: "See income, position, and cash movement whenever you need the answer.", points: ["Income statement", "Balance sheet", "Cash flow reporting"] }, idText: { title: "Laporan keuangan tanpa menunggu", description: "Lihat laba, posisi, dan pergerakan kas kapan pun Anda membutuhkan jawabannya.", points: ["Laporan laba rugi", "Neraca", "Laporan arus kas"] } },
    { id: "budget-forecast", en: { title: "Plan ahead with confidence", description: "Turn historical data into a clearer financial plan for the months ahead.", points: ["Budget planning", "Forecast comparison", "Actionable insights"] }, idText: { title: "Rencanakan masa depan dengan yakin", description: "Ubah data historis menjadi rencana keuangan yang jelas untuk bulan-bulan ke depan.", points: ["Perencanaan anggaran", "Perbandingan forecast", "Insight yang dapat ditindaklanjuti"] } },
    { id: "integrations", en: { title: "Connect the tools you already use", description: "Keep finance data flowing cleanly between LedgerFlow and your business workflow.", points: ["Export-ready data", "Consistent workflows", "Less manual work"] }, idText: { title: "Hubungkan alat yang sudah Anda gunakan", description: "Jaga data keuangan tetap mengalir rapi antara LedgerFlow dan alur kerja bisnis Anda.", points: ["Data siap ekspor", "Workflow konsisten", "Lebih sedikit kerja manual"] } },
    { id: "security-compliance", en: { title: "Security designed into every workflow", description: "Protect your financial data with controls your team can understand and trust.", points: ["Role-based access", "Encrypted data", "Audit-ready activity logs"] }, idText: { title: "Keamanan dalam setiap alur kerja", description: "Lindungi data keuangan dengan kontrol yang mudah dipahami dan dipercaya tim Anda.", points: ["Akses berbasis peran", "Data terenkripsi", "Log aktivitas siap audit"] } },
  ],
  resources: [
    { id: "blog", en: { title: "Finance insights for modern teams", description: "Practical ideas to help your business make better financial decisions.", points: ["Practical finance tips", "Industry insights", "Clear, useful explanations"] }, idText: { title: "Insight keuangan untuk tim modern", description: "Ide praktis untuk membantu bisnis membuat keputusan keuangan yang lebih baik.", points: ["Tips keuangan praktis", "Insight industri", "Penjelasan yang mudah dipahami"] } },
    { id: "guides-tutorials", en: { title: "Guides that make finance easier", description: "Follow clear steps for better bookkeeping habits and financial processes.", points: ["Step-by-step learning", "Practical templates", "Built for business owners"] }, idText: { title: "Panduan yang memudahkan keuangan", description: "Ikuti langkah jelas untuk kebiasaan pembukuan dan proses keuangan yang lebih baik.", points: ["Pembelajaran bertahap", "Template praktis", "Dibuat untuk pemilik bisnis"] } },
    { id: "help-center", en: { title: "Help when you need it", description: "Find answers, get oriented, and keep moving with LedgerFlow.", points: ["Product guidance", "Frequently asked questions", "Support resources"] }, idText: { title: "Bantuan saat Anda membutuhkannya", description: "Temukan jawaban, kenali produk, dan terus bergerak bersama LedgerFlow.", points: ["Panduan produk", "Pertanyaan umum", "Sumber daya dukungan"] } },
    { id: "community", en: { title: "Learn with the finance community", description: "Connect with people building stronger business finances every day.", points: ["Shared best practices", "Professional perspectives", "Growing together"] }, idText: { title: "Belajar bersama komunitas finansial", description: "Terhubung dengan orang-orang yang membangun keuangan bisnis lebih kuat setiap hari.", points: ["Praktik terbaik bersama", "Perspektif profesional", "Bertumbuh bersama"] } },
    { id: "templates", en: { title: "Templates that save time", description: "Start with useful structures rather than an empty spreadsheet.", points: ["Finance-ready formats", "Easy to adapt", "Built for everyday work"] }, idText: { title: "Template yang menghemat waktu", description: "Mulai dengan struktur bermanfaat, bukan dari spreadsheet kosong.", points: ["Format siap keuangan", "Mudah disesuaikan", "Dibuat untuk kerja harian"] } },
  ],
};

export default function MarketingDetailPage() {
  const { section = "products", item = "" } = useParams();
  const { language } = useLanguage();
  const detail = details[section]?.find((entry) => entry.id === item);
  const copy = detail ? (language === "id" ? detail.idText : detail.en) : null;
  const t = language === "id" ? { back: "Kembali ke", start: "Mulai gratis", missing: "Halaman tidak ditemukan" } : { back: "Back to", start: "Start free", missing: "Page not found" };
  if (!copy) return <div className="grid min-h-screen place-items-center bg-white p-6 dark:bg-darkBg"><div className="text-center"><h1 className="text-3xl font-bold">{t.missing}</h1><Link className="mt-5 inline-block text-primary-500" to={`/${section}`}>← {t.back}</Link></div></div>;
  return <div className="min-h-screen bg-white dark:bg-darkBg"><header className="sticky top-0 z-50 border-b border-gray-200/80 bg-white/85 backdrop-blur-xl dark:border-white/10 dark:bg-darkBg/85"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6"><Link to="/" className="flex items-center gap-2"><img src={logo} alt="LedgerFlow" className="h-9 w-9"/><b className="text-gray-900 dark:text-white">LedgerFlow</b></Link><div className="flex gap-2"><LanguageSwitcher/><ThemeSwitcher/></div></div></header><main className="px-5 py-16 sm:py-24"><div className="mx-auto max-w-4xl"><Link to={`/${section}`} className="inline-flex items-center gap-2 text-sm font-semibold text-primary-500"><ArrowLeft size={16}/>{t.back}</Link><div className="mt-10 rounded-[2rem] border border-primary-500/15 bg-gradient-to-br from-primary-50 to-cyan-50 p-8 sm:p-14 dark:from-primary-950/30 dark:to-cyan-950/20"><Sparkles className="h-11 w-11 text-primary-500"/><h1 className="mt-6 text-4xl font-bold leading-tight text-gray-900 dark:text-white sm:text-6xl">{copy.title}</h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-gray-600 dark:text-gray-300">{copy.description}</p><ul className="mt-9 grid gap-3 sm:grid-cols-3">{copy.points.map(point => <li key={point} className="flex gap-2 rounded-xl bg-white/80 p-3 text-sm font-semibold text-gray-700 shadow-sm dark:bg-darkCard dark:text-gray-200"><Check size={18} className="shrink-0 text-primary-500"/>{point}</li>)}</ul><Link to="/register" className="mt-10 inline-flex items-center gap-2 rounded-xl bg-primary-600 px-6 py-3 font-bold text-white">{t.start}<ArrowRight size={18}/></Link></div><div className="mt-12 flex items-center gap-3 text-gray-500 dark:text-gray-300"><ShieldCheck className="text-primary-500"/>LedgerFlow · secure, structured financial operations</div></div></main><Footer/></div>;
}
